### ISSUE TITLE
Use pip-tools to lock down requirements.txt

### ISSUE THREAD

**Issue by julianpistorius** [cyverse/atmosphere#174]
For reproducible, reliable deployments.

Currently when I run `pip-compile --verbose requirements.in` I run into a problem where Atmosphere and its various dependencies require different versions of Python libraries (e.g. requests, djangorestframework, etc.)

**Comment by steve-gregory** [comment]
Yesterday, we were bit by https://github.com/eliben/pycparser/issues/151

We determined this was a good reminder as to *why* we should be using pip-tools 😄

**Comment by julianpistorius** [comment]
This is addressed by #241 and cyverse/rtwo#7

**Comment by julianpistorius** [comment]
Also needed #242 and cyverse/clank#152
