### ISSUE TITLE
Wish List: Push-based UI updates (channels?) combined with Instance Events

### ISSUE THREAD

**Issue by julianpistorius** [cyverse/atmosphere#251]
Problem 1: The UI is often quite out of sync with the state of the cloud and relies on polling the Atmosphere API. (Refer to ATMO-1379)
Problem 2: The Atmosphere service itself is often out of sync with the state of the cloud and relies on polling the cloud provider. (Refer to ATMO-519)

Both these scenarios cause unnecessary load and lag.

Proposed Solution for 1: Instead of polling, the UI registers for events on instances and the Atmosphere service pushes these events to the UI. ([Django Channels](https://channels.readthedocs.io/), [WAMP](http://wamp-proto.org/), etc.)

Proposed Solution for 2: Instead of polling the cloud, Atmosphere registers for cloud events (Nova Notifications [1](http://docs.openstack.org/developer/nova/notifications.html), [2](http://alesnosek.com/blog/2015/05/25/openstack-nova-notifications-subscriber/), [AWS CloudWatch events](http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#ec2_event_type))

**Comment by amit4111989** [comment]
I like Solution 1. I have a rough implementation of something similar w/ django channels. Will be happy to collaborate on a prototype
