### ISSUE TITLE
Suspend/Stop(stutoff) Instance doesn't work as expected 

### ISSUE THREAD

**Issue by xuhang57** [cyverse/atmosphere#268]
Hey Steve,

I tried the suspend/stop instance action on atmosphere and it turns out that it removes my fixed ip and floating ip after I suspend/stop the instance. 

However, I think a user might want to keep their IPs when they want to suspend/stop their instances? I am not sure how Atmosphere is supposed to work here. Do you think it should keep the IPs as well?

**Comment by xuhang57** [comment]
Test it with setting `restore_ip` as False and it works!

**Comment by steve-gregory** [comment]
To complete the loop: In the case of cyverse/atmosphere, we prefer to remove IP addresses from instances when suspending/stopping to make them available for other users, but as you noted setting `restore_ip` to False will disable this functionality.

I don't believe that we currently have a great way for that to be specified in the 'configuration' section of a provider/instance (at this point in time) but it is something we will look into at a future date.

Glad you figured it out! 😄
