### ISSUE TITLE
Probably missing packages in requirements.txt

### ISSUE THREAD

**Issue by xuhang57** [cyverse/atmosphere#287]
@steve-gregory Here is how to reproduce:

```
rm -rf /opt/env/atmo
virtualenv atmo
source /opt/env/atmo/bin/activate
pip install -r /opt/dev/atmosphere/requirements.txt
cd /opt/dev/atmopshere
./run_test.sh
```
And you would see the test cases failed due to a few "no module" error. 

Not sure if you could reproduce this. 
Lucas

**Comment by julianpistorius** [comment]
Hi @xuhang57. For development and testing environments you also need to install the packages from `dev_requirements.txt`. The `requirements.txt` file has just enough dependencies for running the application in production, not for running tests.

Try this:

```bash
pip install -r /opt/dev/atmosphere/requirements.txt -r /opt/dev/atmosphere/dev_requirements.txt
```

**Comment by xuhang57** [comment]
@julianpistorius Thanks so much! This is really helpful. And thanks for sharing the `pip-sync` link. 

Problem solved.
