### ISSUE TITLE
Missing the atmo_sessionid in the api request

### ISSUE THREAD

**Issue by xuhang57** [cyverse/atmosphere#474]
Not really know how to explain this. This is `v27` and I log in with using keystone auth backend. 

It fails at `login(request,login) and I think it is because it is missing the SESSION_KEY in the `request.session` So that DRF doesn't work well.

Related Issue: https://github.com/cyverse/django-cyverse-auth/issues/13

**Comment by xuhang57** [comment]
![screen shot 2017-08-16 at 16 56 28](https://user-images.githubusercontent.com/7245860/29384940-e7375770-82a3-11e7-93f9-396610b902fa.png)

**Comment by xuhang57** [comment]
![screen shot 2017-08-16 at 16 56 34](https://user-images.githubusercontent.com/7245860/29384943-e969a782-82a3-11e7-8f50-7437fc1f0e92.png)

**Comment by xuhang57** [comment]
using django-cyverse-auth-1.0.15 fixes this issue. So the problem is between version 1.1.0 and 1.1.1.

**Comment by lenards** [comment]
@xuhang57 - can you tried to 1.1.3 yet?

**Comment by xuhang57** [comment]
@lenards Tried the latest version and I think the problem still persists. This is hard to debug since the Python traceback is not really helpful.

**Comment by xuhang57** [comment]
solved

**Comment by xuhang57** [comment]
https://github.com/cyverse/django-cyverse-auth/pull/15

**Comment by lenards** [comment]
Thank you for following up Lucas (and for reporting the issue promptly).
