### ISSUE TITLE
Problem: `LibcloudDeploymentError` not imported in tasks/driver

### ISSUE THREAD

**Issue by lenards** [cyverse/atmosphere#491]
It appears there is an error class that is not imported or resolving within the `tasks/driver.py` namespace.

```
NameError: global name 'LibcloudDeploymentError' is not defined
  File "tasks/driver.py", line 972, in _deploy_instance
    _deploy_instance.retry(exc=exc)
```

This being reported within Sentry. 

Source: https://github.com/cyverse/atmosphere/blob/master/service/tasks/driver.py#L972-L985

**Comment by julianpistorius** [comment]
![image](https://user-images.githubusercontent.com/742633/29734771-f32c2f40-89a8-11e7-9c88-c08005359d14.png)
