### ISSUE TITLE
Help me to install and config with Openstack

### ISSUE THREAD

**Issue by thanglq123** [cyverse/atmosphere#645]
Hello everybody,

I search it my source code, i try to install. but it not work fine. :(

Please help me talk to me installation and config with openstack. 

Thank you very much.

**Comment by cdosborn** [comment]
Feel free to reach out to our team at atmo-dev@cyverse.org. Please include information regarding your use-cases, requirements, and openstack setup. As a starting point you will want to consult https://cyverse.github.io/atmosphere-guides/install_guide.html.

**Comment by thanglq123** [comment]
Hi

Thanks for your help. I will try to install with install guide and feed back you soon.

Thank you.
