### ISSUE TITLE
Feature Request: Admin-only button to force state re-sync between atmo and openstack

### ISSUE THREAD

**Issue by beckbw** [cyverse/atmosphere#698]
**Description**:
When atmosphere admins are engaged in support, particularly when emulating a user, the atmosphere state of objects (particularly instances) are often out-of sync with the openstack state of the object. This often prevents or delays live administrative support or forces the administrator to make function requests knowing they'll fail or un-emulated/re-emulate in order to "goose" the synchronization between atmosphere and openstack.

**Feature Request**:
Have a troposphere button available only to admins but that exists also while emulating a user that allows for a "live sync" of the meta-data for the object in question. "live-sync" of instances state is the highest priority, but it would be useful for other objects (volumes, etc) as well.

**Comment by julianpistorius** [comment]
Thanks @beckbw. I think there might be a way to use the old v1 API to force a sync with the database. I'll investigate and let you know.
